/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.*;
import java.lang.Math;
import java.sql.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author SSN
 */
public class Book_Ticket extends javax.swing.JFrame {
    Connection con;
    Statement st ,st1, st2 , st3, st4 ,st5;
    PreparedStatement ps;
    ResultSet rs , rs1 , rs2, rs3, rs4 , rs5;
    String from , to , temp;
    int amount , pnr;
    
    
    //st = con.createStatement();
    /**
     * Creates new form Book_Ticket
     */
    public Book_Ticket() {
        initComponents();
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(this,"Driver Loaded!");
            try {
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","Mega477553");
                //JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
            }
            catch (SQLException ex) {
                Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE,null, ex);
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
    public void Book_Ticket(String From , String To){
        from=From;
        to=To;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tr_no = new javax.swing.JComboBox<>();
        time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        To = new javax.swing.JTextField();
        dest_Time = new javax.swing.JTextField();
        dept_Time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        ticket_Price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        User_ID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Ticket_PNR = new javax.swing.JTextField();
        Generate = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Proceed = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ticket ID Generator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(307, 9, 179, 31);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Train No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(457, 58, 81, 28);

        Tr_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Tr_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tr_noActionPerformed(evt);
            }
        });
        getContentPane().add(Tr_no);
        Tr_no.setBounds(645, 59, 98, 28);

        time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        time.setText("Dept-Time");
        getContentPane().add(time);
        time.setBounds(58, 177, 81, 24);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dest_Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(457, 176, 103, 27);

        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });
        getContentPane().add(From);
        From.setBounds(197, 115, 156, 27);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("From");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(58, 114, 91, 27);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("To");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(457, 111, 91, 32);
        getContentPane().add(To);
        To.setBounds(645, 116, 98, 24);
        getContentPane().add(dest_Time);
        dest_Time.setBounds(645, 178, 98, 24);

        dept_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_TimeActionPerformed(evt);
            }
        });
        getContentPane().add(dept_Time);
        dept_Time.setBounds(197, 178, 156, 24);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("No Of Passengers");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(457, 232, 133, 24);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ticket Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(58, 230, 113, 29);

        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        getContentPane().add(No);
        No.setBounds(645, 234, 100, 22);

        ticket_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_PriceActionPerformed(evt);
            }
        });
        getContentPane().add(ticket_Price);
        ticket_Price.setBounds(197, 233, 156, 24);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(457, 294, 103, 27);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(647, 297, 98, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Reservation Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 340, 130, 28);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText(" Book Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 340, 100, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("User_ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(58, 58, 91, 29);

        User_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_IDActionPerformed(evt);
            }
        });
        getContentPane().add(User_ID);
        User_ID.setBounds(197, 59, 156, 29);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("PNR No");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(58, 294, 113, 26);
        getContentPane().add(Ticket_PNR);
        Ticket_PNR.setBounds(197, 295, 156, 26);

        Generate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Generate.setText("GENERATE");
        Generate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        getContentPane().add(Generate);
        Generate.setBounds(129, 448, 97, 37);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("BACK");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(537, 448, 109, 37);

        Proceed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Proceed.setText("PROCEED");
        Proceed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });
        getContentPane().add(Proceed);
        Proceed.setBounds(326, 448, 116, 37);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\SSN\\Downloads\\MP_Images\\9(1).jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-190, -50, 1230, 750);

        setSize(new java.awt.Dimension(800, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tr_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tr_noActionPerformed

        From.setText(from);
        To.setText(to);
        try {
            String sql1 = "select Dept_Time from STATIONS where St_name = '"+from+"' and Tr_No = '"+Tr_no.getSelectedItem()+"'";
            st1 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs1 = st1.executeQuery(sql1);
            if(rs1.next()){
                dept_Time.setText(rs1.getString(1));
            }
            String sql2 = "select Arr_Time from STATIONS where St_name = '"+to+"' and Tr_No = '"+Tr_no.getSelectedItem()+"'";
            st2 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs2 = st2.executeQuery(sql2);
            if(rs2.next()){
                dest_Time.setText(rs2.getString(1));
            }
        

            String s1 = "select * from Amounts where U_Source = '"+from+"' and U_Dest = '"+to+"'";
            st3 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs3= st3.executeQuery(s1);
            //System.out.println(rs.getString(1));
            if(rs3.next()){
                //System.out.println(rs4.getString(2));
                ticket_Price.setText(rs3.getString(3));
            } 
            else{
               // System.out.println(" You are fool");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_Tr_noActionPerformed

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromActionPerformed

    public void call(){
        try{
            st = con.createStatement();
    
            rs= st.executeQuery("SELECT * FROM Stations S1 JOIN Stations S2 ON S1.Tr_No = S2.Tr_No WHERE S1.St_Name = '"+from+"' AND S2.St_Name = '"+to+"'");
            while(rs.next()){
                String S_From = rs.getString("Tr_No");
                Tr_no.addItem(S_From);
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }
    private void User_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_IDActionPerformed
        // TODO add your handling code here:
        //time1.setText("100");
    }//GEN-LAST:event_User_IDActionPerformed

    private void dept_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dept_TimeActionPerformed

    private void ticket_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticket_PriceActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        //pnr=(int)(Math.random());
    }//GEN-LAST:event_totalActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        try {
            // TODO add your handling code here:
            amount = (Integer.parseInt(No.getText()))* Integer.parseInt((rs3.getString(3)));
            total.setText(String.valueOf(amount));
            //System.out.println(amount);
        } catch (SQLException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            while(true){
                pnr=(int)(Math.random()*(10000+1)+0);
                String s1 = "select Ticket_PNR from TICKET_BOOKS where Ticket_PNR = '"+pnr+"'";
                st4 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                rs4 = st4.executeQuery(s1);
                if(rs4.next()){
                    continue;
                }
                else{
                    Ticket_PNR.setText(String.valueOf(pnr));
                    break;
                }

            }
        }
        catch(Exception ex){
            Logger.getLogger(Insert_User_Details.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_NoActionPerformed

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        // TODO add your handling code here:
       //System.out.println(R_Date.getDateFormatString());
        //CallableStatement stat 
        try{
            String s = "select * from TICKET_BOOKS where Ticket_PNR = '"+pnr+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(s);
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Ticket ID Already Exists");
            }
            else{
                if(Ticket_PNR.getText().equals("") || No.getText().equals("") ||  User_ID.getText().equals("") || Tr_no.getSelectedItem().equals("")  || From.getText().equals("") || To.getText().equals("") || dest_Time.getText().equals("") || dept_Time.getText().equals("")  || ticket_Price.getText().equals("")){
                        JOptionPane.showMessageDialog(this,"Invalid Input!");
                }
                else{
                    try{
                        
                        String sql ="insert into TICKET_BOOKS values(?,?,?,?,?,?,?,?)";
                        ps=con.prepareStatement(sql);
                        ps.setString(1,Ticket_PNR.getText());
                        ps.setInt(2,Integer.parseInt(No.getText()));
                        ps.setString(3,User_ID.getText());
                        ps.setString(4, (String) Tr_no.getSelectedItem());
                        ps.setString(5,from);
                        ps.setString(6,to);
                        SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MMM-YYYY");
                        String date1=sdf1.format(R_Date.getDate());
                        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-YYYY");
                        String date2=sdf2.format(B_Date.getDate());
                        ps.setString(7,date1);
                        ps.setString(8,date2);
                        
                        //ps.setString(8,B_Date.getDateFormatString());
                        System.out.println(date1);
                        ps.execute();
                        JOptionPane.showMessageDialog(this,"Ticket ID Generated");
                    }
                    catch(SQLException ex){
                        Logger.getLogger(Insert_User_Details.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    
                }
                
            }

        }
        catch(Exception ex){
           Logger.getLogger(Insert_User_Details.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
           
        }
    }//GEN-LAST:event_GenerateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        User U = new User();
        U.show();
    }//GEN-LAST:event_BackActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Payment p = new Payment();
        p.payment(Ticket_PNR.getText(), amount , (String) Tr_no.getSelectedItem() ,Integer.parseInt(No.getText()) );
        p.show();
        
    }//GEN-LAST:event_ProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField From;
    private javax.swing.JButton Generate;
    private javax.swing.JTextField No;
    private javax.swing.JButton Proceed;
    private javax.swing.JTextField Ticket_PNR;
    private javax.swing.JTextField To;
    private javax.swing.JComboBox<String> Tr_no;
    private javax.swing.JTextField User_ID;
    private javax.swing.JTextField dept_Time;
    private javax.swing.JTextField dest_Time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ticket_Price;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

}
