/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author SSN
 */
public class Train_Insert extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form Train_Insert
     */
    public Train_Insert() {
        initComponents();
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(this,"Driver Loaded!");
            try {
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","Mega477553");
                //JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
            }
            catch (SQLException ex) {
                Logger.getLogger(Train_Insert.class.getName()).log(Level.SEVERE,null, ex);
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            Logger.getLogger(Train_Insert.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tr_No = new javax.swing.JLabel();
        Tr_Na = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        De = new javax.swing.JLabel();
        S_Ti = new javax.swing.JLabel();
        Sou = new javax.swing.JLabel();
        Dest_Ti = new javax.swing.JLabel();
        Tr_Name = new javax.swing.JTextField();
        Tr_No = new javax.swing.JTextField();
        Source = new javax.swing.JTextField();
        Dest = new javax.swing.JTextField();
        S_Time = new javax.swing.JTextField();
        Dest_Time = new javax.swing.JTextField();
        Cap = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tr_No.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tr_No.setForeground(new java.awt.Color(255, 255, 255));
        tr_No.setText("   Train No");
        getContentPane().add(tr_No);
        tr_No.setBounds(160, 90, 94, 32);

        Tr_Na.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tr_Na.setForeground(new java.awt.Color(255, 255, 255));
        Tr_Na.setText("  Train Name");
        getContentPane().add(Tr_Na);
        Tr_Na.setBounds(160, 140, 94, 33);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INSERT TRAIN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 20, 200, 47);

        C.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("    Capacity");
        getContentPane().add(C);
        C.setBounds(150, 180, 94, 33);

        De.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        De.setForeground(new java.awt.Color(255, 255, 255));
        De.setText(" Destination");
        getContentPane().add(De);
        De.setBounds(160, 280, 94, 33);

        S_Ti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        S_Ti.setForeground(new java.awt.Color(255, 255, 255));
        S_Ti.setText("Staring Time");
        getContentPane().add(S_Ti);
        S_Ti.setBounds(160, 330, 94, 33);

        Sou.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sou.setForeground(new java.awt.Color(255, 255, 255));
        Sou.setText("Starting Point");
        getContentPane().add(Sou);
        Sou.setBounds(160, 230, 120, 33);

        Dest_Ti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dest_Ti.setForeground(new java.awt.Color(255, 255, 255));
        Dest_Ti.setText("Destination Time");
        getContentPane().add(Dest_Ti);
        Dest_Ti.setBounds(160, 380, 130, 33);

        Tr_Name.setForeground(new java.awt.Color(255, 255, 255));
        Tr_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tr_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Tr_Name);
        Tr_Name.setBounds(327, 135, 144, 30);

        Tr_No.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Tr_No);
        Tr_No.setBounds(327, 91, 144, 30);

        Source.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Source);
        Source.setBounds(327, 237, 144, 30);

        Dest.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Dest);
        Dest.setBounds(327, 288, 144, 30);

        S_Time.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(S_Time);
        S_Time.setBounds(327, 339, 144, 30);

        Dest_Time.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Dest_Time);
        Dest_Time.setBounds(327, 390, 144, 30);

        Cap.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Cap);
        Cap.setBounds(327, 186, 144, 30);

        Insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Insert.setText("Insert");
        Insert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert);
        Insert.setBounds(270, 480, 119, 31);

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(120, 500, 70, 34);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(480, 500, 59, 34);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SSN\\Downloads\\MP_Images\\10.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, -80, 830, 830);

        setSize(new java.awt.Dimension(662, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refresh(){
        Tr_No.setText("");
        Tr_Name.setText("");
        Cap.setText("");
        Source.setText("");
        Dest.setText("");
        S_Time.setText("");
        Dest_Time.setText("");
    }
    private void Tr_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tr_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tr_NameActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        try{
           String sql1 = "select * from TRAINS where tr_No = '"+Tr_No.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Train Already Exists");
            }
            else{
                if(Tr_No.getText().equals("") || Tr_Name.getText().equals("") ||  Cap.getText().equals("") || Source.getText().equals("")  || Dest.getText().equals("") || S_Time.getText().equals("") || Dest_Time.getText().equals("") ){
                        JOptionPane.showMessageDialog(this,"Invalid Input!");
                }
                else{
                    try{
                        String sql ="insert into TRAINS values(?,?,?,?,?,?,?)";
                        ps=con.prepareStatement(sql);
                        ps.setString(1,Tr_No.getText());
                        ps.setString(2,Tr_Name.getText());
                        ps.setInt(3,Integer.parseInt(Cap.getText()));
                        ps.setString(4,Source.getText());
                        ps.setString(5,Dest.getText());
                        ps.setString(6,S_Time.getText());
                        ps.setString(7,Dest_Time.getText());
                        ps.execute();
                        JOptionPane.showMessageDialog(this,"Train Inserted");
                    }
                    catch(SQLException ex){
                        Logger.getLogger(Insert_User_Details.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    refresh();
                   
                }
                
            }
        }
        catch(Exception ex){
           Logger.getLogger(Insert_User_Details.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_InsertActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_clearActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Admin Ad = new Admin();
        Ad.show();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Train_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Train_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Train_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Train_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Train_Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel C;
    private javax.swing.JTextField Cap;
    private javax.swing.JLabel De;
    private javax.swing.JTextField Dest;
    private javax.swing.JLabel Dest_Ti;
    private javax.swing.JTextField Dest_Time;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel S_Ti;
    private javax.swing.JTextField S_Time;
    private javax.swing.JLabel Sou;
    private javax.swing.JTextField Source;
    private javax.swing.JLabel Tr_Na;
    private javax.swing.JTextField Tr_Name;
    private javax.swing.JTextField Tr_No;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tr_No;
    // End of variables declaration//GEN-END:variables
}
